FEAT: Eggnog formats and types
bokulich-lab/q2-types-genomics pull request #30
Opened 2022-06-18 00:09 UTC by Keegan-Evans

Clearly not done, but @misialq, I wanted you to be able to see where I was getting with these. I tweaked the formats to be more in line with the most recent document, and tweaked/fixed some of the basic tests. Monday I am going to work on validation for NOG and hopefully get rolling on the OG and KEGG stuff.

2022-07-06 15:17 UTC, misialq commented
Hey @Keegan-Evans, I only now realized that you tagged me for review a while ago... Do you want me to go through the code or are you still working on it? (I _glanced_ through it and so far it seems 👍)

2022-07-18 12:10 UTC, misialq requested changes
Hey @Keegan-Evans, thanks for those new formats! Two high-level comments:
- Could you please rename the test data files using snake case? It's a bit difficult to read the names.
- Please update your branch with the newest `main` to re-run the CI with coverage.

Otherwise, please see some comments inline.

Thanks!

2022-07-18 12:10 UTC, misialq commented on q2_types_genomics/eggnog/_format.py
> +                        i >= self.header + 1 and i < self.footer):
```suggestion
                if (not re.search(r'\t', line) and
                        self.header + 1 <= i < self.footer):
```

2022-07-18 12:10 UTC, misialq commented on q2_types_genomics/eggnog/_validator.py
> +def _check_fields(data: pd.DataFrame, level, reference_fields):
Does this function need the `level` arg? Unless you anticipate some usage in the near future, please remove.

2022-07-18 12:10 UTC, misialq commented on q2_types_genomics/eggnog/_validator.py
> +                   ])
Please replace with a set literal (here and above):
```suggestion
kegg_fields = {'KEGG_ko', 'KEGG_Pathway', 'KEGG_Module', 'KEGG_Reaction',
               'KEGG_rclass', 'BRITE', 'KEGG_TC'}
```

2022-07-18 21:32 UTC, Keegan-Evans commented on q2_types_genomics/__init__.py
> +importlib.import_module('q2_types_genomics.eggnog')
Nope, just put there to keep contained away from other changes(you know in addition to being in a separate branch 😅) I will get them moved over.

2022-07-18 21:32 UTC, Keegan-Evans commented on q2_types_genomics/eggnog/_util.py
> +                print(line)
Yep 😬

2022-07-20 19:01 UTC, Keegan-Evans commented on q2_types_genomics/__init__.py
> +importlib.import_module('q2_types_genomics.eggnog')
https://github.com/Keegan-Evans/q2-types-genomics/commit/1164b485179fff6d2e08ae9f559b8ccd9df89c7d

2022-07-21 00:13 UTC, Keegan-Evans commented on q2_types_genomics/eggnog/tests/test_format.py
> +    using Semantic Validators"""
moved.

2022-07-21 00:13 UTC, Keegan-Evans commented on q2_types_genomics/eggnog/_format.py
> +                    raise ValueError("No correct separator detected in input "
Indeed it should 😅

2022-07-21 00:20 UTC, Keegan-Evans commented on q2_types_genomics/eggnog/tests/test_format.py
> +        print(fmt.header)
yep, removed

2022-07-21 00:22 UTC, Keegan-Evans commented on q2_types_genomics/eggnog/tests/test_validators.py
> +            has_run = True
Yes, but if you put them after running the validation, when the error is raised, then it does not actually end up running the assignment statement 😵‍💫

2022-07-21 00:23 UTC, Keegan-Evans commented on q2_types_genomics/eggnog/tests/test_validators.py
> +        assert has_run
I think I have re-written all of these, I was not sure how I wanted to actually run the validators, as I wanted to make sure they were being run by the framework during view access, I think I have it resolved now.

2023-02-02 21:18 UTC, closed without merging