FEAT: add eggnog mapper types and formats, rebased to follow main.
bokulich-lab/q2-types-genomics pull request #39
Opened 2023-02-20 19:20 UTC by Keegan-Evans

2023-03-03 11:07 UTC, misialq requested changes
Hey @Keegan-Evans, I looked through your changes and one thing that occurred to me is that this PR also has some unrelated updates to the contig formats - in the future, could you please separate such changes into an independent PR? It'd be easier to review as they are not related to functional annotation. Thanks!

Otherwise, see some comments inline.

2023-03-03 11:07 UTC, misialq commented on q2_types_genomics/per_sample_data/tests/test_format.py
> +        format.validate()
Is it really necessary to restructure the entire contig data directory just to add one test? There is a test already for asserting the "good contigs" (which you commented out below?). The only other test (the one right above) could have simply be done by pointing to some other existing directory with no format-acceptable files?

2023-03-03 11:07 UTC, misialq commented on ci/recipe/meta.yaml
> +    - qiime2 {{ qiime2_epoch }}.*
Why is this added here? The tests have worked without it until now.

2023-03-06 15:27 UTC, Keegan-Evans commented on q2_types_genomics/feature_data/__init__.py
> +           ]
Our linter likes it and it reduces the diff on any future additions 🤷‍♂️, I can change it, but as far as I am concerned it is good.

2023-03-06 15:28 UTC, Keegan-Evans commented on q2_types_genomics/genome_data/__init__.py
> +           ]
Keep changing this way how? I think maybe I missed what your complaint was before.

2023-03-10 16:28 UTC, ebolyen commented on q2_types_genomics/feature_data/__init__.py
> +           ]
The original was better, its indentation is cleaner. Please do as Michal requests :)

2023-03-10 16:31 UTC, ebolyen commented on q2_types_genomics/per_sample_data/_format.py
> +    MultiBowtie2IndexDirFmt, BAMDirFmt, MultiBAMDirFmt
There shouldn't be, @Keegan-Evans, use:
```
git checkout main -- q2_types_genomics/per_sample_data/_format.py
```
to reset this file (and ideally similar commands for anything else that didn't need to be touched specifically).

2023-03-10 16:42 UTC, Keegan-Evans commented on q2_types_genomics/per_sample_data/tests/test_format.py
> +
Nope 😅

2023-03-10 16:50 UTC, Keegan-Evans commented on q2_types_genomics/per_sample_data/_format.py
> +    MultiBowtie2IndexDirFmt, BAMDirFmt, MultiBAMDirFmt
It was throwing linting errors at one point(for no apparent reason that I understood 😂)

2023-03-13 09:40 UTC, misialq approved these changes
Hey @Keegan-Evans, many thanks for the clean-ups - all looks good! 🥇 

I saw one test which didn't have any actual code in it, so maybe you could still remove that one (see my comment inline) - otherwise feel free to merge, thanks!

2023-03-13 09:40 UTC, misialq commented on q2_types_genomics/genome_data/tests/test_format.py
> +        dirpath = self.get_data_path('genes')
A little leftover here? :)

2023-04-17 06:25 UTC, misialq approved these changes
Thanks @Keegan-Evans, looks great! 🚀 I'm merging this one!

2023-04-17 06:28 UTC, merged